# This is a config for E2B sandbox template.
# You can use template ID (n8dd7shtn1f3n00elgw4) or template name (vibe-nextjs-amirrezajm) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-amirrezajm") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-amirrezajm") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-amirrezajm')

team_id = "045f5bc7-0580-4f8f-945a-7b817d6a8a95"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-amirrezajm"
template_id = "n8dd7shtn1f3n00elgw4"
